-- 코드를 작성해주세요
SELECT 
CASE 
    WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m-%d') <= '03-31' THEN '1Q'
    WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m-%d') <= '06-30' THEN '2Q'
    WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m-%d') <= '09-31' THEN '3Q'
    ELSE '4Q'
END 'QUARTER', COUNT(ID) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER ASC
